name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build latest push on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install Packages
        run: |
          npm i
      - name: Build appimage
        run: |
          npm run appimage
      - name: Make AppImage dir
        run: mkdir -p finalAppImage/ && mv ./dist/Flash\ Player-*.AppImage ./finalAppImage/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: appimage
          path: finalAppImage/

  build-windows:
     name: Run PSScriptAnalyzer on Windows
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v3
       - name: Setup Node
         shell: bash
         run: nvm install 19 && nvm use 19
       - name: Install dependencies
         shell: bash
         run: npm i
       - name: Build for Window
         shell: bash
         run: npm run windows
